---
- hosts: all

  become: yes
  tasks:
  - name: Install prerequisites
    apt:
      name:
        - apt-transport-https        # It is designed to provide HTTPS protocol support when working with the APT
        - ca-certificates            # Package contains ca-certificates to verify the authenticity of HTTPS connections
        - curl                       # Curl is used in command lines or scripts to transfer data
        - gnupg-agent                # Daemon, which stores GPG secret keys in memory
        - software-properties-common # A set of tools that providees an abstraction for managing APT repositories 
      update_cache: yes
  
  - name: add apt-key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
  
  - name: add docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
  
  - name: install docker
    apt:
      name:
        - docker-ce                   # docker community-edition
        - docker-ce-cli               # docker community-edition-cli
        - containerd.io               # daemon providing low-level management of containers
      update_cache: yes
  
  - name: add userpermissions
    shell: "usermod -aG docker server"

# Installs python venv

  - name: create venv directory
    ansible.builtin.file:
      path: /home/server/venv_py
      state: directory
      owner: server

  - name: install python3.12-venv
    apt:
      name: python3.12-venv
      state: latest

  - name: create virtual environment   
    command: python3 -m venv /home/server/venv_py
    become_user: server 

# Installs Docker SDK
# --
#
# TODO: Make sure you replace user server with your desired administrative 
#       username for your remote server:
#

  - name: install docker-compose-plugin
    apt:
      name: docker-compose-plugin
      state: latest
      update_cache: yes

  - name: install python package manager
    apt:
      name: python3-pip
      
  - name: install python SDK
    become_user: server
    pip:
      name:
        - docker
      virtualenv: /home/server/venv_py
    
      
