---
- name: Python-dependencies
  hosts: all
  become: true

  tasks:
  - name: Install python3-tools
    ansible.builtin.apt:
      pkg:
      - python3
      - python3-setuptools
      - python3-dev
      - build-essential
      - python3-pip
      - default-libmysqlclient-dev
    update_cache: true

